[project]
name = "real-estate-price-predictor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dadata>=25.10.0",
    "requests>=2.34.2",
]

[project.scripts]
real-estate-price-predictor = "real_estate_price_predictor:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
